# Generated by Django 3.2 on 2021-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210421_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('av_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
