# Generated by Django 3.2 on 2021-04-22 08:23

import App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210421_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('pan', models.FileField(upload_to=App.models.pan_upload)),
                ('aadhar', models.FileField(upload_to=App.models.aadhar_upload)),
                ('certificate', models.FileField(upload_to=App.models.certificate_upload)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=0, upload_to=App.models.blog_image_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_image',
            field=models.ImageField(default=0, upload_to=App.models.destination_image_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_documents',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.documents'),
            preserve_default=False,
        ),
    ]
