# Generated by Django 3.2 on 2021-04-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210422_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='charges',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
