# Generated by Django 3.2 on 2021-04-23 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210423_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_documents',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.documents'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(0, True), (1, False)], default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=True),
        ),
    ]
