# Generated by Django 3.2 on 2021-04-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210423_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_documents',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.documents'),
        ),
    ]
