# Generated by Django 3.2 on 2021-04-23 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_guide_guide_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('days_id', models.AutoField(primary_key=True, serialize=False)),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='days_available',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.days'),
        ),
    ]
