# Generated by Django 3.2 on 2021-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20210423_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.ManyToManyField(to='App.Location'),
        ),
    ]
