# Generated by Django 3.2 on 2021-04-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_guide_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='aadhar',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='certificate',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='pan',
            field=models.FileField(upload_to=''),
        ),
    ]
