# Generated by Django 3.2 on 2021-04-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20210423_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='days_available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.days'),
        ),
    ]
