# Generated by Django 3.2 on 2021-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
