# Generated by Django 3.2 on 2021-04-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_remove_guide_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
