# Generated by Django 3.2 on 2021-04-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_review_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.guide')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.location')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tourist')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
