# Generated by Django 3.2 on 2021-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20210424_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dttm',
            field=models.DateTimeField(null=True),
        ),
    ]
