# Generated by Django 3.2 on 2021-04-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_auto_20210425_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='location',
        ),
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.location'),
        ),
    ]
